---
title: "ASI: Introduction to R"
author: |
  | Dr Stevie Pederson
  | EZONE Building
  | University of Western Australia
date: "21-22 November, 2023"
site: workflowr::wflow_site
output: github_document
editor_options:
  chunk_output_type: console
---

```{r, echo=FALSE}
getTiming <- function(f, by = 1, digits = 0){
  ln <- readLines(here::here(f))
  n <- sum(grepl("^#{2} ", ln))
  paste0(round(n * by, digits), "min")
}
```

Run on behalf of the Australian & New Zealand Society of Immunologists

Presented by Black Ochre Data Labs, Telethon Kids Institute

## Setup Instructions

Please find a complete set of instructions for setup [here](installation.html).
It is important that you follow these and have a working installation before 9am Tuesday, November 21st.

All data for the session is available [here](data.zip).

## Tuesday November 21st

|     | Topic | Notes | Estimated Duration |
|:--- |:----- |:----- | ------------------:|
| 8:30 - 9:00   | Installation Help Session | [Installation](installation.html) | 30min |
| 9:00 - 10:30  | General Introduction     | [Introduction](intro.html)      | `r getTiming("intro_slides.qmd", 0.75)`   |
|               | RStudio & R Scripts      | [RStudio](rstudio.html)         | `r getTiming("rstudio_slides.qmd", 1, -1)` |
|               | Bringing Data Into R     | [Data Import](data_import.html) | `r getTiming("import_slides.qmd", 1.5, -1)` |
| 10:30 - 11:00 | Morning Tea Break       |                                 | 30min |
| 11:00 - 13:00 | Bringing Data Into R (cont.) |  | 15min |
|               | Simple Visualisations | [Introduction to `ggplot2`](basic_ggplot2.html) | `r getTiming("import_slides.qmd", 1.5, -1)` |
|               | Working With Text     | [Working With Text](text.html) | `r getTiming("text_slides.qmd", 1.5, -1)` |

## Wednesday November 22nd

|     | Topic | Notes | Estimated Duration |
|:--- |:----- |:----- | ------------------:|
| 9:00 - 10:30  | Working With Spreadsheet-like Data | [Tidying Data Frames](spreadsheets.html)      | `r getTiming("spreadsheet_slides.qmd", 1.5, -1)`   |
